[package]
name = "rsa"
version = "0.1.0"
authors = ["Daniël W. Crompton <daniel.crompton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsa = "0.2.0"
rand = "0.7.3"
